version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    reviewers:
      - "RobThePCGuy"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all-minor-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    reviewers:
      - "RobThePCGuy"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all-minor-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 5
    reviewers:
      - "RobThePCGuy"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"